version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - application

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - application

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    # https://stackoverflow.com/questions/68872388/laravel-and-docker-permission-issue-cant-save-files
    user: "1000:1000"
    container_name: php-fpm
    volumes:
      - ../:/var/www/html
    ports:
      - ${PHP_FPM_PORT}:80
    networks:
      - application

networks:
  application:
